### PR TITLE
Tests now passing

### PR DESCRIPTION
**Pull request by rojalator**
All tests now pass - some were adjusted slightly due to code corrections. Note that this code has links that point to the new documentation, so if accepted, those links would need to be updated (to point back to the mccutchen ones, once those are updated too!).

### CODE REVIEW

**Comment by mccutchen** [comment]
Hi @rojalator, I'm very, very sorry for the complete radio silence on my end.

On your earliest pull requests, I kept drafting small bits of feedback, but you kept closing the pull requests and opening new ones with only incremental changes.  FYI, at least in my experience, the general expectation when collaborating via pull requests on GitHub is that, for a given feature/fix/improvement, a single pull request is opened and then evolved over time in response to feedback (as opposed to opening and closing many pull requests to iterate on the same set of changes).  It's not at all fair to you, but I just didn't have the energy or bandwidth to keep up with the changes.

That being said, I have a proposal for you:  **Would you like to just take over ownership of this project altogether?**  I think I can make you an owner of [the dycco pypi project](https://pypi.org/project/dycco/), and you can switch your fork of this repo over to be the primary source, and do with it what you will.

Please let me know what you think.  If you're interested, we should probably finalize details over email; please reach out to me at [github username] @ gmail!

I haven't used this myself in many many years and have no intention of using it going forward, so will not be investing any additional time in maintenance.

**Comment by rojalator** [comment]
Dear Will,

Apologies for the github mess - my mistake.

I'll be happy to take it over (I've actually put the full version online
in my own repo as I thought you'd disappeared!).

Hope I've sent these to the correct address.

Regards,
RJL

On 23/08/23 19:17, Will McCutchen wrote:
> Hi @rojalator, I'm very, very sorry for the complete radio silence on my end.
> 
> On your earliest pull requests, I kept drafting small bits of feedback, but you kept closing the pull requests and opening new ones with only incremental changes.  FYI, at least in my experience, the general expectation when collaborating via pull requests on GitHub is that, for a given feature/fix/improvement, a single pull request is opened and then evolved over time in response to feedback (as opposed to opening and closing many pull requests to iterate on the same set of changes).  It's not at all fair to you, but I just didn't have the energy or bandwidth to keep up with the changes.
> 
> That being said, I have a proposal for you:  **Would you like to just take over ownership of this project altogether?**  I think I can make you an owner of [the dycco pypi project](https://pypi.org/project/dycco/), and you can switch your fork of this repo over to be the primary source, and do with it what you will.
> 
> Please let me know what you think.  If you're interested, we should probably finalize details over email; please reach out to me at [github username] @ gmail!
> 
> I haven't used this myself in many many years and have no intention of using it going forward, so will not be investing any additional time in maintenance.
> 

-- 
---

**Comment by rojalator** [comment]
Apologies for the github mess - my mistake entirely. Have emailed you.

**Comment by mccutchen** [comment]
Hey @rojalator, I have not yet received an email from you, if you did send one.

**Comment by rojalator** [comment]
Have retried with the address on your github page. It's not like this on Star Trek. I've resent to the address published (I sent one there last night, but no reply).

**Comment by rojalator** [comment]
Received your email - I have been sending to that address.

**Comment by mccutchen** [comment]
Closing this pull request in preparation for archiving this repo.  [rojalator/dycco](https://github.com/rojalator/dycco/) is the new dycco!

**Pull request closed without merging**
